apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniargo-client-1
  namespace: argocd
spec:
  destination:
    namespace: miniargo-client-1
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    helm:
      valueFiles:
      - ../values-override.yaml
      - ../values-applications.yaml
      - ../values-appprojects.yaml
    path: argocd-install/argo-cd
    repoURL: https://github.com/0m1xa/argocd-client1.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true